### ISSUE TITLE
Can't install via Carthage

### ISSUE THREAD

**Issue by haaakon** [akashivskyy/GoogleAnalytics-Framework#1] opened 2015-09-10 12:17 UTC
(develop↓⚡) carthage update  
*** Fetching GoogleAnalytics-Framework
No tagged versions found for github "akashivskyy/GoogleAnalytics-Framework"

Seems like project does not have any tagged versions, so carthage can't install it

**Comment by Torsph** [comment] 2015-09-14 10:43
In carthage you could specify the branch you want to use: 
```
github "akashivskyy/GoogleAnalytics-Framework" "master"
```

**Comment by walsht** [comment] 2015-12-12 11:19
Getting some build failures...
```
*** Building scheme "Google Analytics" in Google Analytics.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Ld /Users/timwalsh/Library/Developer/Xcode/DerivedData/Google_Analytics-beaszcsaebvkjwdnomwxxdjysvdb/Build/Intermediates/Google\ Analytics.build/Release-iphoneos/Google\ Analytics.build/Objects-normal/arm64/GoogleAnalytics normal arm64
	Ld /Users/timwalsh/Library/Developer/Xcode/DerivedData/Google_Analytics-beaszcsaebvkjwdnomwxxdjysvdb/Build/Intermediates/Google\ Analytics.build/Release-iphoneos/Google\ Analytics.build/Objects-normal/armv7/GoogleAnalytics normal armv7
(2 failures)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Users/timwalsh/Library/Developer/Xcode/DerivedData/Google_Analytics-beaszcsaebvkjwdnomwxxdjysvdb/Build/Intermediates/Google\ Analytics.build/Release-iphoneos/Google\ Analytics.build/Objects-normal/arm64/GoogleAnalytics normal arm64
	Ld /Users/timwalsh/Library/Developer/Xcode/DerivedData/Google_Analytics-beaszcsaebvkjwdnomwxxdjysvdb/Build/Intermediates/Google\ Analytics.build/Release-iphoneos/Google\ Analytics.build/Objects-normal/armv7/GoogleAnalytics normal armv7
(2 failures)
```

**Comment by fatuhoku** [comment] 2016-03-16 08:52
Also, are updates to the Google Analytics SDK taken care of?

**Comment by akashivskyy** [comment] 2016-03-17 07:53
@fatuhoku: SDK has been updated to 3.15 in 39cb71084a0e85f6d90bc45b6656fbfc3f6eb79c.

@haaakon: The versions are now tagged (3.12 and 3.15).

@walsht: These errors were caused by unsupported Bitcode settings, please check now with version 3.15.

**Comment by akashivskyy** [comment] 2016-04-29 14:06
Closing this as I cannot reproduce installation errors and the SDK is up-to-date.

**Closed by akashivskyy** 2016-04-29 14:06 UTC
Labels: installation
